create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  phone text not null,
  player_name text not null,
  grad_year text not null,
  position text not null,
  referrer text not null default 'direct',
  status text not null default 'new'
);

create index if not exists waitlist_created_at_idx on public.waitlist (created_at desc);
create index if not exists waitlist_status_idx on public.waitlist (status);

create table if not exists public.demo_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_name text not null,
  grad_year text not null,
  position text not null,
  batting_average text,
  era text,
  video_link text,
  target_schools text,
  report_json jsonb not null
);

create index if not exists demo_reports_created_at_idx
  on public.demo_reports (created_at desc);
