create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  phone text not null,
  player_name text not null,
  grad_year text not null,
  position text not null,
  referrer text not null default 'direct',
  status text not null default 'new'
);

create index if not exists waitlist_created_at_idx on public.waitlist (created_at desc);
create index if not exists waitlist_status_idx on public.waitlist (status);

create table if not exists public.demo_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_name text not null,
  grad_year text not null,
  position text not null,
  batting_average text,
  era text,
  video_link text,
  target_schools text,
  report_json jsonb not null
);

create index if not exists demo_reports_created_at_idx
  on public.demo_reports (created_at desc);

-- Phase 2: Data moat foundation tables (intentionally empty during MVP).
-- These tables are created now so crawlers/UI can be added later without
-- disruptive schema churn.

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  normalized_name text,
  division text,
  conference text,
  city text,
  state text,
  country text default 'USA',
  roster_size integer,
  scholarship_limit numeric(6, 2),
  website text,
  program_status text not null default 'active',
  source text,
  source_url text
);

create unique index if not exists programs_normalized_name_uq
  on public.programs (normalized_name);
create index if not exists programs_division_idx on public.programs (division);
create index if not exists programs_conference_idx on public.programs (conference);

create table if not exists public.program_refresh_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running',
  trigger text,
  started_by text,
  parsed_count integer,
  deduped_count integer,
  upserted_count integer,
  website_count integer,
  coach_count integer,
  quality_updates integer,
  error_message text,
  run_context jsonb not null default '{}'::jsonb
);

create index if not exists program_refresh_runs_started_at_idx
  on public.program_refresh_runs (started_at desc);
create index if not exists program_refresh_runs_status_idx
  on public.program_refresh_runs (status);

create table if not exists public.coaches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  program_id bigint references public.programs(id) on delete set null,
  first_name text,
  last_name text,
  full_name text not null,
  role text,
  email text,
  phone text,
  recruiting_coordinator boolean not null default false,
  is_active boolean not null default true,
  source text,
  source_url text
);

create index if not exists coaches_program_id_idx on public.coaches (program_id);
create index if not exists coaches_email_idx on public.coaches (email);
create index if not exists coaches_full_name_idx on public.coaches (full_name);

create table if not exists public.hs_players (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  external_player_id text,
  first_name text,
  last_name text,
  full_name text not null,
  grad_year integer,
  primary_position text,
  secondary_positions text[],
  height text,
  weight_lbs integer,
  bats_throws text,
  hometown_city text,
  hometown_state text,
  hometown_country text default 'USA',
  school_name text,
  gpa numeric(4, 2),
  sat_score integer,
  act_score integer,
  video_url text,
  source text,
  source_url text
);

create unique index if not exists hs_players_external_player_id_uq
  on public.hs_players (external_player_id)
  where external_player_id is not null;
create index if not exists hs_players_grad_year_idx on public.hs_players (grad_year);
create index if not exists hs_players_primary_position_idx
  on public.hs_players (primary_position);

create table if not exists public.program_needs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  program_id bigint not null references public.programs(id) on delete cascade,
  recruiting_cycle_year integer not null,
  position text not null,
  need_score numeric(5, 2),
  graduating_count integer not null default 0,
  committed_count integer not null default 0,
  transfer_out_count integer not null default 0,
  notes text,
  source text,
  source_url text
);

create unique index if not exists program_needs_cycle_position_uq
  on public.program_needs (program_id, recruiting_cycle_year, position);
create index if not exists program_needs_cycle_year_idx
  on public.program_needs (recruiting_cycle_year);

create table if not exists public.commitments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  external_commitment_id text,
  hs_player_id bigint references public.hs_players(id) on delete set null,
  player_name text not null,
  grad_year integer,
  position text,
  committed_program_id bigint references public.programs(id) on delete set null,
  committed_program_name text,
  committed_level text,
  commitment_date date,
  source_handle text,
  source text,
  source_url text,
  confidence numeric(4, 3) not null default 0.70,
  raw_payload jsonb not null default '{}'::jsonb
);

create unique index if not exists commitments_external_commitment_id_uq
  on public.commitments (external_commitment_id)
  where external_commitment_id is not null;
create index if not exists commitments_program_idx
  on public.commitments (committed_program_id);
create index if not exists commitments_commitment_date_idx
  on public.commitments (commitment_date desc);
create index if not exists commitments_grad_year_idx on public.commitments (grad_year);

create table if not exists public.showcases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  external_showcase_id text,
  organizer text,
  event_name text not null,
  start_date date,
  end_date date,
  city text,
  state text,
  country text default 'USA',
  venue text,
  event_url text,
  cost_usd numeric(10, 2),
  estimated_attendance integer,
  recruiting_level text,
  source text,
  source_url text
);

create unique index if not exists showcases_external_showcase_id_uq
  on public.showcases (external_showcase_id)
  where external_showcase_id is not null;
create index if not exists showcases_start_date_idx on public.showcases (start_date);
create index if not exists showcases_organizer_idx on public.showcases (organizer);

create table if not exists public.showcase_outcomes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  showcase_id bigint not null references public.showcases(id) on delete cascade,
  hs_player_id bigint references public.hs_players(id) on delete set null,
  player_name text,
  offers_reported integer not null default 0,
  commitments_generated integer not null default 0,
  followup_contacts integer not null default 0,
  roi_score numeric(6, 2),
  notes text,
  source text,
  source_url text
);

create index if not exists showcase_outcomes_showcase_idx
  on public.showcase_outcomes (showcase_id);
create index if not exists showcase_outcomes_player_idx
  on public.showcase_outcomes (hs_player_id);
