import type { ProgramInput } from "@/lib/schemas";

export const starterSchools: ProgramInput[] = [
  {
    name: "Vanderbilt University",
    division: "D1",
    conference: "SEC",
    city: "Nashville",
    state: "TN",
    website: "https://vucommodores.com/sports/baseball/",
    source: "starter_seed",
  },
  {
    name: "University of Tennessee",
    division: "D1",
    conference: "SEC",
    city: "Knoxville",
    state: "TN",
    website: "https://utsports.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Louisiana State University",
    division: "D1",
    conference: "SEC",
    city: "Baton Rouge",
    state: "LA",
    website: "https://lsusports.net/sports/bsb/",
    source: "starter_seed",
  },
  {
    name: "University of Florida",
    division: "D1",
    conference: "SEC",
    city: "Gainesville",
    state: "FL",
    website: "https://floridagators.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Texas A&M University",
    division: "D1",
    conference: "SEC",
    city: "College Station",
    state: "TX",
    website: "https://12thman.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Arkansas",
    division: "D1",
    conference: "SEC",
    city: "Fayetteville",
    state: "AR",
    website: "https://arkansasrazorbacks.com/sport/m-basebl/",
    source: "starter_seed",
  },
  {
    name: "University of Texas at Austin",
    division: "D1",
    conference: "SEC",
    city: "Austin",
    state: "TX",
    website: "https://texassports.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of North Carolina",
    division: "D1",
    conference: "ACC",
    city: "Chapel Hill",
    state: "NC",
    website: "https://goheels.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Wake Forest University",
    division: "D1",
    conference: "ACC",
    city: "Winston-Salem",
    state: "NC",
    website: "https://godeacs.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Clemson University",
    division: "D1",
    conference: "ACC",
    city: "Clemson",
    state: "SC",
    website: "https://clemsontigers.com/sports/baseball/",
    source: "starter_seed",
  },
  {
    name: "University of Virginia",
    division: "D1",
    conference: "ACC",
    city: "Charlottesville",
    state: "VA",
    website: "https://virginiasports.com/sports/mbaseball/",
    source: "starter_seed",
  },
  {
    name: "Duke University",
    division: "D1",
    conference: "ACC",
    city: "Durham",
    state: "NC",
    website: "https://goduke.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Florida State University",
    division: "D1",
    conference: "ACC",
    city: "Tallahassee",
    state: "FL",
    website: "https://seminoles.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Miami",
    division: "D1",
    conference: "ACC",
    city: "Coral Gables",
    state: "FL",
    website: "https://miamihurricanes.com/sports/baseball/",
    source: "starter_seed",
  },
  {
    name: "Stanford University",
    division: "D1",
    conference: "ACC",
    city: "Stanford",
    state: "CA",
    website: "https://gostanford.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Oregon",
    division: "D1",
    conference: "Big Ten",
    city: "Eugene",
    state: "OR",
    website: "https://goducks.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of California, Los Angeles",
    division: "D1",
    conference: "Big Ten",
    city: "Los Angeles",
    state: "CA",
    website: "https://uclabruins.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Southern California",
    division: "D1",
    conference: "Big Ten",
    city: "Los Angeles",
    state: "CA",
    website: "https://usctrojans.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Oregon State University",
    division: "D1",
    conference: "Independent",
    city: "Corvallis",
    state: "OR",
    website: "https://osubeavers.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of California, Irvine",
    division: "D1",
    conference: "Big West",
    city: "Irvine",
    state: "CA",
    website: "https://ucirvinesports.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Dallas Baptist University",
    division: "D1",
    conference: "Conference USA",
    city: "Dallas",
    state: "TX",
    website: "https://dbupatriots.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "East Carolina University",
    division: "D1",
    conference: "AAC",
    city: "Greenville",
    state: "NC",
    website: "https://ecupirates.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Southern Mississippi",
    division: "D1",
    conference: "Sun Belt",
    city: "Hattiesburg",
    state: "MS",
    website: "https://southernmiss.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Connecticut",
    division: "D1",
    conference: "Big East",
    city: "Storrs",
    state: "CT",
    website: "https://uconnhuskies.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Campbell University",
    division: "D1",
    conference: "CAA",
    city: "Buies Creek",
    state: "NC",
    website: "https://gocamels.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "University of Tampa",
    division: "D2",
    conference: "Sunshine State",
    city: "Tampa",
    state: "FL",
    website: "https://tampaspartans.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "North Greenville University",
    division: "D2",
    conference: "Conference Carolinas",
    city: "Tigerville",
    state: "SC",
    website: "https://www.nguathletics.com/sports/bsb/",
    source: "starter_seed",
  },
  {
    name: "University of Central Missouri",
    division: "D2",
    conference: "MIAA",
    city: "Warrensburg",
    state: "MO",
    website: "https://ucmathletics.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Trinity University",
    division: "D3",
    conference: "SCAC",
    city: "San Antonio",
    state: "TX",
    website: "https://trinitytigers.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Johns Hopkins University",
    division: "D3",
    conference: "Centennial",
    city: "Baltimore",
    state: "MD",
    website: "https://hopkinssports.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Hope International University",
    division: "NAIA",
    conference: "GSAC",
    city: "Fullerton",
    state: "CA",
    website: "https://athletics.hiuroyals.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Southeastern University",
    division: "NAIA",
    conference: "The Sun Conference",
    city: "Lakeland",
    state: "FL",
    website: "https://fireseu.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Walters State Community College",
    division: "JUCO",
    conference: "TCCAA",
    city: "Morristown",
    state: "TN",
    website: "https://wsccathletics.com/sports/baseball",
    source: "starter_seed",
  },
  {
    name: "Central Arizona College",
    division: "JUCO",
    conference: "ACCAC",
    city: "Coolidge",
    state: "AZ",
    website: "https://www.centralaz.edu/athletics/baseball/",
    source: "starter_seed",
  },
];
